<?php 
    $userChoise = $_GET["username"];
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>
            Le héros c'est toi!
        </title>
    </head>
    <body>
        <form action="page2.phtml" method="GET">
           <section>
                <fieldset>
                    <label for="username">
                        Quel est votre nom, héros ?
                    </label>
                    <input type="text" id="username" name="username"/>
                </fieldset>
                
                <fieldset>
                    <button type="submit">
                        COMMENCER VOTRE AVENTURE
                    </button>
                </fieldset>
            </section> 
        </form>
            <section>
                <img src=""></img>
                <h1>
                    Le site dont vous etes le héros
                </h1>
            </section>
            <script src="main.js"></script>
    </body>
</html>