<?php
$username = "";
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <link href="style.css" rel="stylesheet">
        <h1>
            Le héros c'est toi!
        </h1>
    </head>
    <body>
        <main>
            <form action="page2.phtml" method="GET">
               <section>
                    <fieldset>
                        <label for="username">
                            Quel est votre nom, héros ?
                        </label>
                        <input type="text" id="username" name="username"/>
                    </fieldset>
                    
                    <fieldset>
                        <button type="submit">
                            COMMENCER VOTRE AVENTURE
                        </button>
                    </fieldset>
                </section> 
            </form>
                <section>
                    <h2>
                        Le site dont vous etes le héros
                        <img src="https://cdn1.ftimg.com/images/logos/big/fr_FR/super-hero-logo.png"/>
                    </h2>
                </section>
                <script src="main.js"></script>
        </main>
    </body>
</html>