<?php 
    
    /*$maVariable = $_GET["monNomDeVariable"];*/
?>
<!DOCTYPE html>
<html lang="fr">
    <head>
        <meta charset="utf-8" />
        <title>
            Le héros c'est toi!
        </title>
    </head>
    <body>
        <main>
            <form action="" method="GET">
               <section>
                    <fieldset>
                        <label for="personnage">Choisie ton personnage</label>
                        <input type="radio" id="personnage" name="personnage"/>
                       
                        <label for="personnage1">PERSONNAGE 1</label>
                        <input type="radio" id="" name="personnage1" img src="" />
                        
                        <label for="personnage2">PERSONNAGE 2</label>
                        <input type="radio" id="" name="personnage2"/>
                        
                        <label for="personnage3">PERSONNAGE 3</label>
                        <input type="radio" id="" name="personnage3"/>
                    </fieldset>
                    
                    <fieldset>
                        <button type="submit">
                            CONTINUER
                        </button>
                    </fieldset>
                </section> 
            </form>
                <section>
                    <img src=""></img>
                    <h1>
                        Le site dont vous etes le héros
                    </h1>
                </section>
        </main>
    </body>

</html>